#!/usr/bin/env node

"use strict";

var fs = require('fs')
  , es = require('event-stream')
  , _ = require('underscore')

var path = process.argv.length > 2 ? process.argv[2] : '/usr/share/dict/words'
var entries = {}
fs.readFile(path, 'utf-8', function(err, data) {
  _.each(data.split('\n'), function(word) {
    entries[word] = true
  })

  process.stdin.setEncoding('utf-8')
  process.stdin
    .pipe(es.split())
    .pipe(es.map(function(line, cb) {
      line = line.replace(/[^ \n]+/g, function(match) {
        if (entries[match.toLowerCase()]) {
          return match
        } else {
          return '<' + match + '>'
        }
      })
      cb(null, line)
    }))
    .pipe(es.join('\n'))
    .pipe(process.stdout)
})

